### PR TITLE
docs: rm uri

### PR DESCRIPTION
**Pull request by 1ethanhansen**
# The problem

internal uri exposed to public docs

# This PR's solution

change to example as per slack conversation

# Checklist

_Check that this PR satisfies the following items:_

- [x] Tests have been added for new features/changed behavior (if no new features have been added, check the box).
- [x] The [changelog file](CHANGELOG.md) has been updated with a user-readable description of the changes (if the change isn't visible to the user in any way, check the box).
- [x] The PR's title is prefixed with `<feat/fix/chore/imp[rovement]/int[ernal]/docs>[!]:`
- [x] The PR is linked to a JIRA ticket (if there's no suitable ticket, check the box).

### CODE REVIEW

**Review by alexjuda — APPROVED** [review]
Thanks for catching that!

**Comment by SebastianMorawiec** [comment]
@1ethanhansen seems like one of the tutorial tests are failing: FAILED tests/sdk/v2/test_api_tutorial_scripts.py::test_config_management - As...

I can help you debug it if you want

**Comment by 1ethanhansen** [comment]
@SebastianMorawiec I think I know what the problem is... Let me try to fix and I'll ping you if I still need help debugging!

**Comment by 1ethanhansen** [comment]
When I made the PR I didn't realize that these files were actually test files, I thought they were just examples for the docs. Since they are test files, this whole PR is flawed: changing to example.orquestra.io means the tests will necessarily fail. If it doesn't harm things too much to leave the URI exposed, we can just leave it as-is

**Comment by jamesclark-Zapata** [comment]
@1ethanhansen All our examples in docs are tests!

**Comment by 1ethanhansen** [comment]
@jamesclark-Zapata yeah that's AWESOME!! Wish they were all like that 🥇

**Pull request closed without merging**
