### PR TITLE
chore!: Merge breaking changes to main

### PR DESCRIPTION
**Pull request by jamesclark-Zapata**
This is a collection of breaking changes.

Please merge this (i.e. not squash!) when ready.

### CODE REVIEW

**Review by alexjuda — CHANGES_REQUESTED** [review]
Artificially requesting changes to prevent it from being merged until we're ready

**Comment by alexjuda** [comment]
Uh oh, we have some conflicts with `main`. @zapatacomputing/sdk-team WDYT about the following branching strategy?
1. If possible, merge feature PRs to `main`, with a single squashed PR commit (as usual)
2. Temporarily, if there's a big breaking change, merge the PIR with a single squash commit to `breaking-changes` (this branch).
3. To keep `main` and `breaking-changes` in sync, we use a "standard" rebase to maintain a linear-ish history.
4. When `breaking-changes` is no longer needed, we close this PR with a rebase, but no squash. This will let the PR squash commits made against `breaking-changes` also show up on `main`

**Comment by alexjuda** [comment]
Rebased to fix the conflicts after https://github.com/zapatacomputing/orquestra-workflow-sdk/commit/d4e35822c705503255674b5542edb310277cc42e

**Comment by alexjuda** [comment]
Another rebase after https://github.com/zapatacomputing/orquestra-workflow-sdk/commit/265baeb5bbe13814aa9f36090c912b4f7265709e

**Comment by jamesclark-Zapata** [comment]
Rebased on `main`

**Comment by jamesclark-Zapata** [comment]
Rebased on `main` after fe6e8078d1badf99a5b64afbefa98bb56280c9be

**Review by alexjuda — APPROVED** [review]

**Review by SebastianMorawiec — APPROVED** [review]

**Pull request merged**
